linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unconvert
    - misspell
    - gosec
    - prealloc
    - gocritic

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated

  gosec:
    excludes:
      - G204  # Subprocess launched with variable

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
