name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install revive
        run: go install github.com/mgechev/revive@latest

      - name: Run gofmt
        run: |
          files=$(gofmt -l .)
          if [ -n "$files" ]; then
            echo "The following files need formatting:"
            echo "$files"
            exit 1
          fi

      - name: Run go vet
        run: go vet ./...

      - name: Run revive
        run: revive -config revive.toml -formatter friendly ./...
